{% set name = "oath" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ab990e530ebbc607f67d7df34c5d26147a7d431bae54dcfb44b3704b04dbd0f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - oath

about:
  home: https://github.com/bdauvergne/python-oath
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'Python implementation of HOTP, TOTP and OCRA algorithms from OATH'

  description: |
    python-oath is a package implementing the three main OATH specifications
    *   HOTP, an event based one-time password standard -- OTP -- using HMAC signatures,
    *   TOTP, a time based OTP,
    *   OCRA, a mixed OTP / signature system based on HOTP for complex use cases.
  doc_url: https://github.com/bdauvergne/python-oath
  dev_url: https://github.com/bdauvergne/python-oath

extra:
  recipe-maintainers:
    - kynan
