travis:
  secure:
    BINSTAR_TOKEN: idhp2fFILqyAqR4xeuyVnkePJVIWGzZWYp/E8H1EE+eB72NG9Lc6dpWgd0QJcH3DHE1Oo0eUfEtbYEA6C9VTbNzE+ZOT3FSaLOlDbmYWp/hcVbQ53l3Xvvw8ivOePpxbYADW1ay4pBU/N2xblzhFxp3GWUSWKRflKYsAqOJdyMO4B8ntASS7pNarJLDcGS60MszCm5+2LNTYe2/ERyG+Kvh/+hm38H7dEZoUPJGheqm8OU+l3yRyE1s6uWkEdFzvN2XCY5CoVF5BpG3fAz+Ke7Wt9YODXkQlyLuNy1tFIJ4MwZ0xPb2KPbd3id9uJMf+yhbRvyHJfzJD77Npal44pgIbC16vGCR2B3m91aJwJ/ortb8+unOuwqdkA88gAJ48f63h8TRlAerVploWo4KO4TU9FPZCpx0IGSjzvl7TfZmSTECGyVybtoZYZ9TVLf5AzeQYLxKiZsa/TVC/ETpCcbS5KKrhbjuwvmZT/38Mgc4jQPawsFEopAsVPfIbbO+zbE+eIDGaYJdm+MSl+xYlCve+rld8b+oJQFlSUs8N0qqICOA39yI9thBaXePZLRIk4bZrkv8PJ3uF4lu+VfJnJofTMTa8Chgu9MXKL1EQGvwn7RZnil4MCjKtnHSloTYkMOQHYOxSsHWHqf3CH900jaIbuZnEWoNC0Du2kkPqsWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
