travis:
  secure:
    BINSTAR_TOKEN: sOEVMKQhhsUTVQ0xMw6gvYnOk5VHgw+pEo5ODIpFT8lUQGmZcRirD52kTUYQ/5d5OEt2Cg/sAkzeYX/tujz7X4ul6RN/URXVK/yH2LtCpluGGyhBKgR4W7Mj8bmhznjJpqHVpCJhvHmyam7SUl0ns89lvuJ5eS/JhScMhgavb0zPAAeh5IEEAYULO/1vlGiL+6rFJ7FKqgTnz2tGPZCL++dB2NVajV0nGoLxc3RZfbm0MGLSTOuTpk90RJlunzR8idRMaKpTxzklNpnzLAI2xjkYwzGSMm2Y/DzkbuMylQYM2lgF94OiOfR6c7AXFVMeMtMhuQkwDJKh1H2z/6UKsx6EeqM0hc79dw9sgiv8EbSZPTwCdy3n8/waowRW961gK6uR5/fE38kRosNiWbbW4Tzlw5oJ8UKUijZjdYdDF0/3cYv2keOxXe5TZhp5hsqQ3IvbG8981cUq/Y/jF0HEA1PyC7i8Sgck0R8cU0l2lFAz6l+alfIzwx0TW5Ysy1yYuYLVOGcqJvXluya1iJlHvIrqwyskgs8eYf96/y72YkWXb6wVXNiXMkb0WxxceaAFpNL9cJ0wDqRPDToMVuJH4XCRgVrQT4Qg1h6yPgr/4PjSq0TexiXUouaktiqmqbsnDw8tpeno8CRKsjLErQkcebqTrRCcBMOV9qCvNnyIqGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
